### ISSUE TITLE
What's the difference between DeePSD and DeePSDchi? 

### ISSUE THREAD

**Issue by shawkontzu** [HugoBA92/DeePSD#2]
Hi, what's the difference between DeePSD and DeePSDchi? Why do you train them separately? 
Thank you.

**Comment by hbertiche** [comment]
DeePSD predicts two sets of blend shapes,
one is learnt supervisedly from data, without taking into account body collisions or cloth-like behaviour,
the other one is learnt unsupervisedly (chi) by enforcing physical constraints as losses, also, a regularization term ensures these extra deformations are minimal,

because of this, while it is possible to train both branches at the same time, we observe no advantage on training 'chi' before the supervised part of the model has converged, thus, we train them separately,
also note that the unsupervised approach allows combinations of template outfits and poses that are not present on the dataset, therefore, it is also convinient to train it in a separate script with a different data pipeline,

I hope I could answer your question, please do not hesitate to ask further doubts

**Comment by shawkontzu** [comment]
@HugoBA92 Thank you for the reply. About training them separately, do you mean train_chi.py will train completely from scratch or we can give the previously train model from train.py as the checkpoints input param for train_chi.py? 

Thank you!

**Comment by hbertiche** [comment]
train_chi.py will expect a checkpoint,
the correct usage would be, first:
`python train.py [GPU_ID] my_model`
this will train DeePSD supervisedly, later:
`python train_chi.py [GPU_ID] model_with_chi my_model`
it will train only 'chi' using the previously trained model ('my_model'),

at the beginning of both scripts (around lines 17-24) you will find a brief explanation of script args,
for both of them we have
-gpu: slot of gpu to use, it can be multiple ones, examples ["1", "1,2", ""]
-name: it will save model checkpoints with this name like "[name].npy" in the "checkpoints/" folder
-checkpoint: it will try to load a pre-trained model located at "checkpoints/[checkpoint].npy". this argument is optional for 'train.py', but mandatory for 'train_chi.py'
the models are implemented with a checkpoint loading functionality that checks the list of variables and reports any differences found between the model architecture and the variables found in the checkpoint, it will still load those variables that have the same name and shape,
