### ISSUE TITLE
Bug in Train_CHI - Training is not happening

### ISSUE THREAD

**Issue by lokender** [HugoBA92/DeePSD#5]
There is a bug somewhere in the train_chi code. The error came out to be 0.000 starting from the first batch. After debugging it seems the body mesh is not correct and hence the losses. Attached is the screenshot of the body mesh we get from pred, pred_chi, **body** = model(...) (Line 82 train_chi.py)
![Screenshot from 2022-01-11 13-05-19](https://user-images.githubusercontent.com/3035262/148900841-e012acb6-b54a-41c3-af9e-1b40846e6561.png)

@HugoBA92 Can you please check this?

**Comment by hbertiche** [comment]
I tried to reproduce this,
the function that computes the SMPL mesh is located in 'Model/DeePSDchi.py' at lines 199-206, the method is called '_transforms()'
it takes poses as Nx72 arrays, shapes as Nx10 arrays and genders as N arrays, where N is the batch size, it takes an additional input 'with_body' that must be set to 'True' to also compute the SMPL mesh, otherwise it will return 'None' as the mesh (for efficiency when it is not needed),
as outputs, it gives the transformation matrices of each joint as N x K x 4 x 4 (with K as the number of joints) and the body mesh as N x V x 3 (with V equal the number of vertices),
the method internally calls the SMPLModel defined in 'Model/smpl/smpl_np.py' with the given parameters for each batch sample,

I tested this function with the sequence '00070' of CLOTH3D dataset (the dataset used in DeePSD paper), and it behaves as expected, I do not obtain the results that you show on your image or anything like that,
<img width="182" alt="00070" src="https://user-images.githubusercontent.com/16307925/149932442-b65172aa-7f05-4731-b6a6-21db1843decb.png">

because of this, I would ask you to make sure that the pose data that you are feeding to the model is correct,

I hope I could help you,
please do not hesitate to ask further questions

**Comment by lch32111** [comment]
I also have the similar problem as lokender.

My inference code is fairly simple and I just copied the code in the train_chi.py for the inference.
I used the Cloth3D data for training and inference. There are no changes on the DeePSD code and training/inference data.
It seems that there is a problem on smpl code.

Here is the body by my renderer:
![image](https://github.com/hbertiche/DeePSD/assets/19434311/e7baf6d4-ed3a-4e09-abc5-e5a636875370)


This is the inference code:
```
import os
import sys
import pickle
from datetime import datetime
import numpy as np
import tensorflow as tf

from Data.data import Data
from Model.DeePSDchi import DeePSD

""" ARGS """
# gpu_id : GPU slot to run model
# checkpoint : trained model (must be in ./checkpoints/ folder)
# gpu_id = sys.argv[1]
# checkpoint = 'checkpoints/' + sys.argv[2]
gpu_id = '0'
checkpoint = 'your_check_point'
output_folder = 'your_check_point'

""" GPU """
os.environ['CUDA_DEVICE_ORDER'] = 'PCI_BUS_ID'
os.environ['CUDA_VISIBLE_DEVICES'] = gpu_id

""" MODEL """
print("Building model...")
model = DeePSD(128, checkpoint)

""" DATA """
print("Reading data...")
batch_size = 1
tr_data = Data('DeePSD/Data/train.txt', batch_size=batch_size, mode='test')

batch = tr_data.next()

idx = list(range(batch_size))
pred, pred_chi, body = model(
    batch['template'],
    batch['laplacians'],
    batch['poses'][idx],
    batch['shapes'],
    batch['genders'],
    batch['fabric'],
    batch['tightness'],
    batch['indices'],
    with_body=True
)

time_str = datetime.now().strftime('%y_%m_%d_%H_%M_%S')
with open(output_folder + 'c3d_' + time_str + '.pkl', 'wb') as f:
    pickle.dump(
        {
            'v': pred.numpy()[np.newaxis, ...],
            'v_chi': pred_chi.numpy()[np.newaxis, ...],
            'b': body,
            'cloth_faces': batch['faces'],
            'body_faces': model.SMPL[0].faces
        },
        f
    )
```

**Comment by lch32111** [comment]
I found the bug. The bug is caused by the mix of chumpy and numpy library. Maybe it can be caused by some version of numpy and chumpy. You can solve this problem by just converting all the chumpy data of SMPL pickle into numpy array. This bug seems to exist on other codes of a line of your research code, which share the same SMPL code.
